- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.dotfiles: ''
    ~/.gitconfig:
    ~/.gitignore_global:
    ~/.agignore:
    ~/.aria2/aria2.conf:
    ~/.axelrc:
    ~/.bash:
    ~/.bash_profile:
    ~/.bashrc:~/.editrc:
    ~/.emacs.d:
    ~/.emacs:~/.gnupg/dirmngr.conf: gnupg/dirmngr.conf
    ~/.gnupg/gpg.conf: gnupg/gpg.conf
    ~/.haskeline:
    ~/.hgrc:
    ~/.inputrc:
    ~/.ipython/profile_default/ipython_config.py: ipython/ipython_config.py
    ~/.ipython/profile_default/ipython_kernel_config.py: ipython/ipython_kernel_config.py
    ~/.ipython/profile_default/startup/disable_warnings.py: ipython/disable_warnings.py
    ~/.irssi:
    ~/.pythonrc:
    ~/.rtorrent.rc:
    ~/.screenrc:
    ~/.shell:
    ~/.tmux.conf:
    ~/.vim:
    ~/.vimrc:
    ~/.zsh:
    ~/.zshrc:

- shell:
  - git submodule sync --recursive
  # the following have to run after linking ~/.gitconfig
  - git update-submodules
  - >
    git cleanall -f
    emacs.d/vendor/
    irssi/scripts/vendor/
    shell/plugins/
    vim/pack/vendor/start/
    zsh/plugins/
